= Sonarqube Operator

== Overview

This repository contains the code to build a Sonarqube Operator for Kubernetes, including Red Hat OpenShift Container Platform.

The Operator will create a *PostgreSQL* database and a *SonarQube* instance connected to the PostgreSQL database.

It is implemented on top of the Red Hat https://sdk.operatorframework.io/[Operator SDK] - in particular the https://sdk.operatorframework.io/docs/building-operators/ansible/[Ansible Operator].

== Building the Operator

There is a script `hack/operate.sh` which will download the prerequisites (operator-sdk etc.), build the operator artifacts from operator-sdk defaults, package and push the operator container image, deploy the artifacts to a Kubernetes cluster, and create a `kind: Sonarqube` CR to deploy an instance. You should use the help page to look at what the various options do, but for the most part if you want to deploy SonarQube to a cluster directly from this repo you could run `hack/operate.sh -d`.

Before running the script make sure to update the location of the container image to a repository you have access to. If you decide to build your own container image for the operator, make sure to update `hack/operate.conf` with an updated container image location and add the `-p` flag to `operate.sh`.

== Installation

=== Operator Installation Steps

The installation of the Custom Resource Definition and Cluster Role requires *cluster-admin* privileges. After that regular users with `admin` privileges on their projects (which is automatically granted to the user who creates a project) can provision the SonarQube Operator in their projects and deploy instances of Sonarqube using the sonarqube.redhatgov.io Custom Resource.

Perform the following tasks as *cluster-admin*:

. Deploy the CustomResourceDefinition, ClusterRole, ClusterRoleBinding, ServiceAccount, and Operator Deployment:
+
[source,sh]
----
hack/operate.sh
----

. Once the Operator pod is running the Operator is ready to start creating SonarQube Servers.

. To deploy the above, and also the `config/samples/redhatgov_v1alpha1_sonarqube.yaml` example CustomResource:
+
[source,sh]
----
hack/operate.sh -d
----

== Deploying a custom SonarQube instance using the Operator

A SonarQube instance is deployed by creating a Custom Resource based on the sonarqube Custom Resource Definition.

.Example
+
[source,texinfo]
----
apiVersion: redhatgov.io/v1alpha1
kind: Sonarqube
metadata:
  name: sonarqube-example
spec:
  postgresql:
    volumeSize: 1Gi
    image:
      src: registry.redhat.io/rhel8/postgresql-10
      tag: latest
  sonarqube:
    expose:
      ssl: true                                             # There is currently no way to specify an alternate certificate
      uri: special-sonarqube-route.apps.cluster.example.com # You can leave this field out on OpenShift to get the default
      kind: Ingress                                         # This can be of kind Route on OpenShift
    image:
      src: quay.io/redhatgov/sonarqube
      tag: latest
      pullPolicy: IfNotPresent
    volumeSize: 1Gi                                         # Only matters if `persistent: true`
    resources:
      memory:
        request: 2Gi
        limit: 3Gi
      cpu:
        request: 1000m
        limit: 2000m
  persistent: true

----

. Write the definition to a file (e.g. sonarqube.yaml) and then create the SonarQube instance:
+
[source,sh]
----
oc create -f ./sonarqube.yaml
----

. The operator will first create the PostgreSQL database, wait until it is up and running and then create the SonarQube pod.
. Validate that both pods (postgresql and sonarqube) are running before proceeding.
. You can validate the existence of your SonarQube instance by querying for sonarqube objects:
+
[source,sh]
----
oc get sonarqube
----

. Get the Route for SonarQube (the PostgreSQL database is not accessible outside of the project):
+
[source,sh]
----
oc get route
----

. Use the hostname returned in your Web Browser to open the SonarQube UI (default User ID is `admin` with password `admin`).

== Deleting a SonarQube instance

Deleting a SonarQube instance and its associated resources is as simple as deleting the sonarqube object. If you created a SonarQube server called `sonarqube-example` as in the example above it suffices to run the delete command on that resource:

[source,sh]
----
oc delete sonarqube sonarqube-example
----

The Operator adds ownerReference fields to all created objects - which means that deleting the sonarqube object also deletes all objects that have been created by the Operator.

== Uninstalling the SonarQube Operator

In case you wish to uninstall the SonarQube Operator make sure that there are no more SonarQube instances running. Once all SonarQube instances have been deleted simply delete the operator and its resources with:
+
[source,sh]
----
hack/operate.sh -r
----

== Notes on disconnected installations

The Operator SDK makes heavy use of Kustomize for development and installation, but intends bundles to be generated for use in an operator catalog. This enables the Operator Lifecycle Manager, deployed onto your cluster, to install and configure operators with a simple `kind: Subscription` object, instead of a large collection of manifests. If you intend on using `hack/operate.sh` it expects you to be in a development environment. Operator installation from this script therefore expects access to the internet. This comes with one extra concern: If `kustomize` isn't in your path, it tries to download it from the internet and save it locally into a `.gitignore`d folder. If you intend on using `hack/operate.sh` to install the operator, you should also bring `kustomize` and place it in the `$PATH` of the user who will be running the script.

To change the image sources for all necessary images for `hack/operate.sh` to deploy the operator, you need to have the following images hosted in a container repository on your disconnected network:

. quay.io/redhatgov/sonarqube-operator:latest
. quay.io/redhatgov/sonarqube:latest
. Some PostgreSQL 10 image that either behaves like the Red Hat PostgreSQL 10 RHEL 8 image or the docker.io/library/postgres:10 image.

The places where you must update those sources are then, respectively:

. `hack/operate.conf`: IMG should point to the sonarqube-operator image in your environment _before_ running `hack/operate.sh`
. The `kind: Sonarqube` custom resource manifest: `spec.sonarqube.image.src` and `spec.sonarqube.image.tag` should be updated
. The `kind: Sonarqube` custom resource manifest: `spec.postgresql.image.src` and `spec.postgresql.image.tag` should be updated

== OLM installation using a custom catalog source

WIP
